// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpsqzmnyrvdahrczeayd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwc3F6bW55cnZkYWhyY3plYXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzA3NDYsImV4cCI6MjA1Mzg0Njc0Nn0.y3EGGZr_WTF4ARphwZRHy7mA3evd15DlE-0Xgx67BMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);